//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Call
    {
        public int id { get; set; }
        public string email { get; set; }
        public string request { get; set; }
        public string name { get; set; }
    }
}
