//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Posts
    {
        public int Post_id { get; set; }
        public string Post_Title { get; set; }
        public string Post_Summery { get; set; }
        public string Post_Description { get; set; }
        public System.DateTime Post_Date { get; set; }
        public string Post_Image { get; set; }
        public int Post_Userid { get; set; }
        public int Post_Catid { get; set; }
        public Nullable<bool> Post_IsBreaking { get; set; }
    
        public virtual Tbl_Cat Tbl_Cat { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
